name: Sync Image to Aliyun

on:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 登录阿里云镜像仓库
        uses: docker/login-action@v3
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: 拉取并推送 ingress-nginx controller 镜像
        run: |
          docker pull registry.k8s.io/ingress-nginx/controller:1.3.0
          docker tag registry.k8s.io/ingress-nginx/controller:1.3.0 registry.cn-beijing.aliyuncs.com/wordpress-duanfeiyu/ingress-nginx-controller:1.3.0
          docker push registry.cn-beijing.aliyuncs.com/wordpress-duanfeiyu/ingress-nginx-controller:1.3.0
