name: Sync Image to Aliyun

on:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 登录阿里云镜像仓库
        uses: docker/login-action@v3
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: 拉取并推送 nginx 镜像
        run: |
          docker pull nginx:1.28.3
          docker tag nginx:1.28.3 registry.cn-beijing.aliyuncs.com/wordpress-duanfeiyu/nginx:1.28.3
          docker push registry.cn-beijing.aliyuncs.com/wordpress-duanfeiyu/nginx:1.28.3
